name: CI

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  NODE_VERSION: [18.x]
  YARN_VERSION: 1.22.19

on:
  push:
    branches:
      - '**'

jobs:
  # LINTERS
  linters_js:
    name: Linters JS
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set up NPM authentication
        run: |
          echo "always-auth=true" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.READ_GITHUB_PKG_TOKEN }}" >> ~/.npmrc
          echo "@strongsdcom:registry=https://npm.pkg.github.com/" >> ~/.npmrc
      - name: Install Node.js dependencies
        run: |
          yarn policies set-version ${{ env.YARN_VERSION }}
          yarn install
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ github.token }}
          eslint: true
          prettier: true
